### PR TITLE
Galician translate

### PR DESCRIPTION
**Pull request by ninjum**
translation into the Galician language, alpha version pending corrections, only file core at the moment

### CODE REVIEW

**Comment by cazfi** [comment]
Ticket to handle this: https://redmine.freeciv.org/issues/929

- bootstrap/langnames.txt needs to be updated too.
- At least dummy translation files needed for nations/ and ruledit/ translation domains too - some parts of the code do not support having translation of one domain but not the others

**Comment by cazfi** [comment]
You may want to join freeciv translations mailing list: https://www.freelists.org/list/freeciv-i18n

**Comment by ninjum** [comment]
added translations of nations and rulesets, and updated the langnames.txt, now if you confirm that everything is correct to be able to join the root, I will start improving the translation of the files.

 I'm already signed up on the freeciv translations mailing list.

**Comment by cazfi** [comment]
It fails to build, because LINGUAS has the country code ("gl_ES") but the actual files do not "gl.po". I think there should be no country code, as this is "main" Galician, not Spanish variant of it.

**Comment by ninjum** [comment]
error fixed, I hope

**Comment by cazfi** [comment]
There was some more issues, but there's now working version attached to the ticket.

> Ticket to handle this: https://redmine.freeciv.org/issues/929

I plan to merge that to all branches once 3.1.3 release has been made. You may want to wait with the further translation updates until this build system level integration is in place.

**Comment by cazfi** [comment]
Patch from the ticket pushed to main and S3_2 branches. S3_1 is pending 3.1.3 release.

This PR was about the main branch -> closing already, despite S3_1 situation

**Pull request closed without merging**
