### PR TITLE
Update mongol.ruleset

### PR DESCRIPTION
**Pull request by rvid19**
Made so that Mongolia has China as a civil war nation. (As they conquered China in real life)

### CODE REVIEW

**Comment by cazfi** [comment]
Ticket to handle this: https://osdn.net/projects/freeciv/ticket/48715

Your patch does not apply to S3_1 or S3_0, and at least to S3_1 I'd like to have it (S3_0 is soon EOL anyway). Can you provide version for those too (either as a attachment to the ticket, or separate github PR)

**Comment by rvid19** [comment]
@cazfi I'm having some problems doing that. It doesn't work.

**Comment by cazfi** [comment]
Ok, I can look backport these myself, then. Not sure if we retain your commit authority, or will you be credited only in commit messages. Depends on what the backporting takes.

**Comment by cazfi** [comment]
Merged outside github UI.

**Pull request closed without merging**
