### PR TITLE
Update chumash.ruleset.

### PR DESCRIPTION
**Pull request by rvid19**
https://github.com/freeciv/freeciv-web/issues/441

### CODE REVIEW

**Comment by cazfi** [comment]
For any freeciv change, ticket in https://osdn.net/projects/freeciv/ticket/ will be needed -> https://osdn.net/ticket/newticket.php?group_id=12505 to track it. The code change can be github PR.

As for this particular change, as far as I know the current name is the correct one. Have you confirmed that it somehow breaks also freeciv? I would assume that the problem in freeciv-web.org is some html encoding one. Fix might be needed in https://github.com/freeciv/freeciv-web, though I'd prefer fixing the root cause (if it's an escaping problem, it can very well have also security implications)

**Comment by cazfi** [comment]
Tested by moving 'Ataxis the first city in the list, and founding dozen cities. First one got named 'Ataxis, and the name was not suggested for any of the others.

**Comment by cazfi** [comment]
freeciv-web was a bit harder to test (no editor mode etc), but essentially the same test passed there too. Name 'Ataxis was suggested for the first city only.

**Comment by rvid19** [comment]
Hi, I haven't tested it in Freeciv, only in Freecivweb. But I got the issue. I guess too it's a html encoding issue. Maybe it works with replacing all `  with &#39;.

**Comment by cazfi** [comment]
> Hi, I haven't tested it in Freeciv, only in Freecivweb. But I got the issue.

With https://github.com/freeciv/freeciv-web codebase? (meaning you've set up your own server to do the test). Or only on some fork run on some public server? (Just because I saw Lexxie's name on that freeciv-web ticket, I for some reason assumed that the report was about her https://www.freecivweb.org/ )

**Comment by rvid19** [comment]
I tested it in https://www.freecivweb.org/

**Pull request closed without merging**
