### PR TITLE
Female Kibutznik is Kibutznikit

### PR DESCRIPTION
**Pull request by yarons**
Changed to the correct form

### CODE REVIEW

**Comment by cazfi** [comment]
Freeciv issue tracking is at http://www.hostedredmine.com/projects/freeciv/issues/new Please open a ticket there.

**Comment by yarons** [comment]
It requires a username and a password and there's no way to register.

**Comment by cazfi** [comment]
There should be "Register" link in the top right corner.

**Comment by cazfi** [comment]
I opened the ticket: http://www.hostedredmine.com/issues/829168

**Comment by yarons** [comment]
Thank you for your help!

**Pull request closed without merging**
