### PR TITLE
Update generate_packets.py

### PR DESCRIPTION
**Pull request by GettingStartedInEveOnline**
Changed line 80.
Could you please tell us why you want compatibility with Python 1.5-2.2 instead of migrating higher? Also I would really like to see something on this project like a "hello world" for python ai api hooks: just something that gets the player's world data as it's generated and lets you move your first settler, so that it's easy to start on writing a different AI. I have no idea how to approach this yet because I'm still getting started in programming.

### CODE REVIEW

**Comment by GettingStartedInEveOnline** [comment]
Changed line 80.
Could you please tell us why you want compatibility with Python 1.5-2.2 instead of migrating higher? Also I would really like to see something on this project like a "hello world" for python ai api hooks: just something that gets the player's world data as it's generated and lets you move your first settler, so that it's easy to start on writing a different AI. I have no idea how to approach this yet because I'm still getting started in programming. (Noob at github also)

**Comment by cazfi** [comment]
Please open a ticket about the patch at http://www.hostedredmine.com/projects/freeciv/issues/new for reviewing it.

Our python scripts work with the latest python versions, and practically with all the older ones. You may have seen some ancient comment from the time when python-2.2 was the latest.

Freeciv scripting language is lua. http://www.freeciv.org/wiki/Event_scripting

**Comment by GettingStartedInEveOnline** [comment]
When you say "the patch", do you mean my adjustments to the code (ambiguous vs my request of a python api).

**Comment by GettingStartedInEveOnline** [comment]
Hey there, no worries.
This was just a refactor, so don't sweat it.

**Pull request closed without merging**
