### PR TITLE
Use pkg-config to find freetype

### PR DESCRIPTION
**Pull request by Polynomial-C**
As of freetype-2.9.1 the freetype-config script no longer gets installed
by default.

See also [Make installation of `freetype-config' optional](http://git.savannah.gnu.org/cgit/freetype/freetype2.git/commit/?id=a7833f26c4ac45cafe1dffdcd7f7dcfd6493161c) commit by freetype upstream. 

The master branch already contains nearly the same code although doing the version check wrong. freetype uses the libtool specific version numbers in its `freetyp2.pc` file. 
See http://git.savannah.gnu.org/cgit/freetype/freetype2.git/tree/docs/VERSIONS.TXT

### CODE REVIEW

**Comment by cazfi** [comment]
Please open tickets about this patch and master bug; http://www.hostedredmine.com/projects/freeciv/issues/new

**Comment by Polynomial-C** [comment]
Done: http://www.hostedredmine.com/issues/754206

**Comment by eisterman** [comment]
Any news on the merge? The installation from source in Archlinux is very problematic without this update

**Comment by Polynomial-C** [comment]
Fixed through commit 3c2cea61e0b1e4e3e97ed98be3f2149fb24edd6f

**Pull request closed without merging**
