### PR TITLE
meson.build

### PR DESCRIPTION
**Pull request by MarkusVolk**
Hello,
i'm using the yocto/oe build environment to cross-compile freeciv for my rock-pi. Since autotools normally aren't the best choice for cross-compiling i decided to go with the experimental meson build system. After some patching  this did work quite well. Here are the patches i needed to get it up and running. Perhaps they could be of use.

### CODE REVIEW

**Comment by cazfi** [comment]
> Hello, i'm using the yocto/oe build environment to cross-compile freeciv for my rock-pi. Since autotools normally aren't the best choice for cross-compiling i decided to go with the experimental meson build system. After some patching this did work quite well. Here are the patches i needed to get it up and running. Perhaps they could be of use.

I've not seen such problems cross-compiling with autotools, or existing meta-games OpenEmbedded recipe that is based on them. In fact, OpenEmbedded is still better supported by our autotools build than in-development meson build (there are configure options on autotools useful some platforms that are not yet available in meson based build).

I think the latter commit is wrong - those tilesets use "normal" building graphics, not the large ones.

That probably means that the first patch is a bit wrong too in not adding those normal building graphics.

Did you make your recipe from scratch? If not, I would be interested to see the changes you did to build with meson. That's where we should eventually go with the meta-games recipe too.

**Comment by MarkusVolk** [comment]
> I think the latter commit is wrong - those tilesets use "normal" building graphics, not the large ones.
> 
> That probably means that the first patch is a bit wrong too in not adding those normal building graphics.

Thats right. These three files also haven't been installed yet and the overrides for them were missing also. Changed that and it's working out of the box on my machine under wayland/sway without the incorrect patch now. All the tilesets get loaded and on a first look everything seems ok. But i'm not an expert to freeciv, will have to get into it first.

> Did you make your recipe from scratch? If not, I would be interested to see the changes you did to build with meson. That's where we should eventually go with the meta-games recipe too.

I started using the recipe from meta-games. It built for me but i got a qa-warning about system-poison-directories. Have been interested in the meson buildsystem anyway and decided to try out what is working. I ended up with a recipe that is more or less written from scratch. It includes two more patches. The first one removes 'meson.get_cross_property' that failed and was not needed. The second is just a hack to use tolua from the host machine without having to include it to HOSTTOOLS because i was too lazy to create a recipe for it.

https://github.com/MarkusVolk/meta-retro-wayland/tree/honister/recipes-games/freeciv

**Comment by cazfi** [comment]
Opened a ticket about this: https://osdn.net/projects/freeciv/ticket/43199

Github Pull Requests are fine, but we need tickets about (almost) all the changes that go in, regardless of what way they have been contributed.

**Comment by cazfi** [comment]
Merged outside github UI, with updated commit message.

**Pull request closed without merging**
