### PR TITLE
Update portuguese.ruleset

### PR DESCRIPTION
**Pull request by rvid19**
Some updates to the Portuguese:
* New monarchs. (Some of the most important ones.)
* Extended legend.

### CODE REVIEW

**Comment by cazfi** [comment]
I guess the ruleset loading errors seen on CI tests are due to an extra comma in the end.

**Comment by rvid19** [comment]
@cazfi Probably. I'll change that. Any feedback on my edits btw?

**Comment by cazfi** [comment]
> @cazfi Probably. I'll change that. Any feedback on my edits btw?

The other patch was already merged. This one has been marked ready for review just now (in osdn).

**Comment by cazfi** [comment]
Merged outside github UI.

**Pull request closed without merging**
