### PR TITLE
Losslessly optimize PNG images

### PR DESCRIPTION
**Pull request by anthonyryan1**
Using Efficient-Compression-Tool we can compless the PNG images without changing the visual appearance.

Save 3.68 MB (14.7% of PNG bytes on average)

I've done a playthrough after optimizing the images and saw no visual change.

### CODE REVIEW

**Comment by cazfi** [comment]
We should leave flags outside this particular patch. Maybe in another commit we could change the flag svg -> png conversion script to do the optimization?

**Comment by anthonyryan1** [comment]
I (mistakenly) assumed flags would remain relatively constant, countries don't change them very often and historical nation flags will never change.

For the SVG -> PNG process, I feel like the Efficient-Compression-Tool I used in this pull request is not viable. It's slow, and not bundled on most distributions.

optipng is probably a viable compression step for flag generation, it's much faster and widely available.

**Comment by cazfi** [comment]
Opened a ticket for handling (including review period) this -> https://osdn.net/projects/freeciv/ticket/46552

**Comment by cazfi** [comment]
Pushed outside github UI. Thanks.

**Comment by cazfi** [comment]
Forget to say that your contribution should show up on OpenHUB next time they refresh their data about freeciv: https://www.openhub.net/p/freeciv/contributors/summary
You may claim those contributions to your own account, if you wish.

**Pull request closed without merging**
