### PR TITLE
Add highways to trident and hex2t tilesets

### PR DESCRIPTION
**Pull request by petervdmeer**
The highways are added at a 3 to 4 pixels offset to railroads, this allows both to be visible on the same tile, while still allowing them to connect as well. (Depending on if the ruleset wants those roads to connect or be separate.)

### CODE REVIEW

**Comment by cazfi** [comment]
The new files need to be added to tarball distribution and get installed too. This need to be done for both legacy autotools and new meson based build system. Former requires changes to relevant Makefile.am, and latter to meson.build.

**Comment by petervdmeer** [comment]
Files are added to the meson.build and Makefile.am files.

I've tested 'ninja' and 'ninja install' and the new files ended up in the (custom) install directory for Meson. I've also tested 'make' and 'make install'. The new files also ended up in the (other custom) install directory.

**Comment by cazfi** [comment]
Ticket to handle this: https://redmine.freeciv.org/issues/255

**Comment by cazfi** [comment]
Merged outside github UI.

**Pull request closed without merging**
